// <auto-generated />
using System;
using DoAnCoSo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnCoSo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240410075259_Initail")]
    partial class Initail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnCoSo.Models.tbChiTietNoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuocThiId")
                        .HasColumnType("int");

                    b.Property<int>("NoiDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuocThiId");

                    b.HasIndex("NoiDungId");

                    b.ToTable("tbChiTietNoiDung");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbChiTietQuyDinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuocThiId")
                        .HasColumnType("int");

                    b.Property<int>("QuyDinhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuocThiId");

                    b.HasIndex("QuyDinhId");

                    b.ToTable("tbChiTietQuyDinh");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbCuocThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonThiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongThiSinh")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonThiId");

                    b.ToTable("tbCuocThi");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbLoaiTruong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiTruong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbLoaiTruong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbMonThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenMonThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbMonThi");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbNoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NoiDungThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbNoiDung");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbPhieuDangKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuocThiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CuocThiId");

                    b.ToTable("tbPhieuDangKy");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbPhieuKetQua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<int>("Giay")
                        .HasColumnType("int");

                    b.Property<int>("PhieuDangKyId")
                        .HasColumnType("int");

                    b.Property<int>("Phut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhieuDangKyId");

                    b.ToTable("tbPhieuKetQua");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbQuyDinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NoiDungQuyDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbQuyDinh");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbTruong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LoaiTruongId")
                        .HasColumnType("int");

                    b.Property<string>("TenTruong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiTruongId");

                    b.ToTable("tbTruong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbChiTietNoiDung", b =>
                {
                    b.HasOne("DoAnCoSo.Models.tbCuocThi", "CuocThi")
                        .WithMany("NoiDungs")
                        .HasForeignKey("CuocThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.tbNoiDung", "NoiDung")
                        .WithMany("ChiTietNoiDungs")
                        .HasForeignKey("NoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuocThi");

                    b.Navigation("NoiDung");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbChiTietQuyDinh", b =>
                {
                    b.HasOne("DoAnCoSo.Models.tbCuocThi", "CuocThi")
                        .WithMany("QuyDinhs")
                        .HasForeignKey("CuocThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.tbQuyDinh", "QuyDinh")
                        .WithMany("ChiTietQuyDinhs")
                        .HasForeignKey("QuyDinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuocThi");

                    b.Navigation("QuyDinh");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbCuocThi", b =>
                {
                    b.HasOne("DoAnCoSo.Models.tbMonThi", "MonThi")
                        .WithMany("CuocThi")
                        .HasForeignKey("MonThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonThi");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbPhieuDangKy", b =>
                {
                    b.HasOne("DoAnCoSo.Models.tbCuocThi", "CuocThi")
                        .WithMany("PhieuDangKys")
                        .HasForeignKey("CuocThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuocThi");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbPhieuKetQua", b =>
                {
                    b.HasOne("DoAnCoSo.Models.tbPhieuDangKy", "PhieuDangKy")
                        .WithMany("PhieuKetQuas")
                        .HasForeignKey("PhieuDangKyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuDangKy");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbTruong", b =>
                {
                    b.HasOne("DoAnCoSo.Models.tbLoaiTruong", "LoaiTruong")
                        .WithMany("Truongs")
                        .HasForeignKey("LoaiTruongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiTruong");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbCuocThi", b =>
                {
                    b.Navigation("NoiDungs");

                    b.Navigation("PhieuDangKys");

                    b.Navigation("QuyDinhs");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbLoaiTruong", b =>
                {
                    b.Navigation("Truongs");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbMonThi", b =>
                {
                    b.Navigation("CuocThi");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbNoiDung", b =>
                {
                    b.Navigation("ChiTietNoiDungs");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbPhieuDangKy", b =>
                {
                    b.Navigation("PhieuKetQuas");
                });

            modelBuilder.Entity("DoAnCoSo.Models.tbQuyDinh", b =>
                {
                    b.Navigation("ChiTietQuyDinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
